### ISSUE TITLE
Test on multiple data inputs in feature files

### ISSUE THREAD

**Issue by HansinieJ** [surenr/CodeSpec#22]
It would be better if the testers can automate feature files using large number of input data via csv files rather than giving the test data within the feature file.

**Comment by agentmilindu** [comment]
Giving large number of inputs is possible with Scenario outlines. 

Writing your tests in the following way will actually generate multiple tests with different parameters for the `<placeholders>`

```
Scenario Outline: Google for Cats
    Given I navigate to "http://google.com"
    And I enter value "<animal>" to the "searchBox" with the "id" of "lst-ib"
    And I click on element "searchButton" with the "xpath" of "id('sblsbb')/button" and wait "4" seconds
    Then The page contains text pattern "<txt>"

    Examples:
    | animal | txt                 |
    | cat    | The domestic cat is |
    | dog    | The domestic dog is |
```
