### ISSUE TITLE
No Specflow Grammar is defined for Keyword "Then"

### ISSUE THREAD

**Issue by HansinieJ** [surenr/CodeSpec#24]
Then(@"""(._)""st row, ""(._)""st column of table ""(._)"" contains value ""(._)""") is already declared but cannot used to find a table cell element like "row one and column three" cell. or for an example Then(@"""(._)""st row, ""(._)""rd column of table ""(._)"" contains value ""(._)""") is not a valid grammar.

**Comment by agentmilindu** [comment]
Fixed in #29 
`Grammar for reading HTML table cell values updated`
